In [1]:
import pandas as pd

In [3]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset,drop_first = True)

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
indep = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [7]:
dep = dataset['charges']

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {'criterion':['squared_error','friedman_mse','absolute_error','poisson'],
            'max_features': ['auto','sqrt','log2'],
            'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3, n_jobs = -1)
grid.fit(indep,dep)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
16 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
24 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.81819656 0.83274776 0.82017872 0.83342237
        nan        nan 0.81743908 0.83351831 0.82205184 0.83243787
        nan        nan 0.81699152 0.83224735 0.81725974 0.83134213
        nan        nan 0.81645325 0.83480495 0.81133121 0.83455905]
  warnings.warn(

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [12]:
re = grid.cv_results_
print(" The R_score for best parameter {} :". format(grid.best_params_))

 The R_score for best parameter {'criterion': 'poisson', 'max_features': 'sqrt', 'n_estimators': 100} :

In [13]:
table = pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004432,0.002043,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.002488,0.000722,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.106115,0.005333,0.012954,0.002043,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.831908,0.765705,0.847448,0.816048,0.829873,0.818197,0.028071,11
3,0.859969,0.033244,0.040858,0.002547,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.856873,0.778471,0.861312,0.828702,0.838382,0.832748,0.029638,5
4,0.097599,0.003992,0.010673,0.000890,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.843892,0.759857,0.853061,0.821892,0.822192,0.820179,0.032525,10
5,0.843850,0.020060,0.039284,0.006392,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.862965,0.776238,0.861494,0.829341,0.837074,0.833422,0.031499,4
6,0.003217,0.000303,0.000000,0.000000,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.002973,0.000294,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.092470,0.000924,0.009646,0.000193,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.837603,0.758600,0.853777,0.819959,0.817257,0.817439,0.032235,12
9,0.858450,0.026796,0.039554,0.002890,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.857877,0.777147,0.863715,0.830519,0.838333,0.833518,0.030709,3
10,0.088793,0.003283,0.009567,0.001164,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.838228,0.762263,0.846791,0.824891,0.838086,0.822052,0.030703,9
11,0.873634,0.020330,0.038303,0.001945,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.856619,0.776424,0.858189,0.830282,0.840675,0.832438,0.029859,6
12,0.003666,0.000715,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.003547,0.000623,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.286772,0.019877,0.009585,0.000763,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.839080,0.767462,0.841470,0.810531,0.826414,0.816992,0.027095,14
15,2.753031,0.089324,0.037887,0.000866,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.855096,0.779610,0.857480,0.829140,0.839911,0.832247,0.028276,7
16,0.291995,0.010665,0.009321,0.001289,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.832539,0.765797,0.832814,0.821727,0.833423,0.817260,0.026096,13
17,2.728007,0.174790,0.035908,0.005914,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.857533,0.781311,0.850747,0.829226,0.837893,0.831342,0.026881,8
18,0.003167,0.000449,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.002851,0.000108,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.102045,0.003345,0.008871,0.000208,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.828653,0.774624,0.842124,0.815054,0.821811,0.816453,0.022752,15
21,0.948509,0.008945,0.038418,0.001806,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.860292,0.783998,0.864091,0.827884,0.837760,0.834805,0.028793,1
22,0.101780,0.006598,0.009031,0.000405,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.843906,0.743596,0.844169,0.813126,0.811859,0.811331,0.036691,16
23,0.887639,0.047224,0.035628,0.002932,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.857365,0.781775,0.860615,0.832783,0.840257,0.834559,0.028358,2

In [14]:
age_input = float(input("Age:"))
bmi_input = float(input("BMI:"))
children_input = float(input("CHILDREN:"))
sex_male_input = int(input("Sex Male 0 or 1:"))
smoker_yes_input = int(input("Smoker Yes 0 or 1:"))

Age: 30
BMI: 66
CHILDREN: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 0

In [15]:
Future_prediction = grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_predictio = {}:".format(Future_prediction))

Future_predictio = [6803.5237063]:

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(